<?php
/**
 * @var App\Blocks\FooterBlock $this;
 */
?>

<footer class="header-footer block">
    <div class="footer">
        <section class="footer__text">
            <div class="footer__content-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </div>

            <span class="footer__copyright">
        © 2022 Taganrog. All rights reserved
      </span>
        </section>

        <nav class="footer__nav">
            <h6 class="footer__nav-header">
                quick Links
            </h6>

            <?php foreach ($this->data['quickLinks'] as $link): ?>
            <a
                href=""
                class="footer__link"
            >
                <?= $link ?>
            </a>
            <?php endforeach; ?>
        </nav>

        <nav class="footer__nav">
            <h6 class="footer__nav-header">
                page Links
            </h6>

            <?php foreach ($this->data['pageLinks'] as $link): ?>
            <a
                href=""
                class="footer__link"
            >
                <?= $link ?>
            </a>
            <?php endforeach; ?>
        </nav>

        <div class="footer__logo logo">
            <div class="footer__logo_padding">
                <a class="logo__word">
                    auto
                </a>

                <a class="logo__word logo__word_light">
                    auto
                </a>

                <a class="logo__word">
                    auto
                </a>

                <a class="logo__word logo__word_light">
                    auto
                </a>

                <a class="logo__word">
                    auto
                </a>
            </div>
        </div>
    </div>
</footer>
