<?php
/**
 * @var App\Blocks\LineBlock $this
 * @var App\Models\LineModel $data
 * @var App\Models\BrandModel $brandModel
 * @var App\Models\Model $item
 */
?>

<?php $data = $this->getData() ?>
<?php $brandModel = $this->getChildModels()['BrandModel'] ?>

<div class="car-info block">
    <section class="car-info__img">
        <form
            class="form"
            method="post"
            action="/carLine"
        >
            <div class="form__row">
                <a>
                    ID:
                </a>
                <input
                    class="form__input"
                    type="number"
                    value="<?= $data->getId() ?>"
                    readonly
                    name="lineId"
                >
            </div>
            <div class="form__row">
                <a>
                    Name:
                </a>
                <input
                    class="form__input"
                    type="text"
                    value="<?= $data->getName() ?>"
                    name="lineName"
                >
            </div>
            <input type="submit" value="SUBMIT">
        </form>
    </section>

    <h1 class="car-info__title">
        <?= $this->getHeader() ?>
    </h1>

    <div class="info">
        <section class="info-stat">
            <div class="info-stat__content">
                <h2 class="info-stat__title stat-title">
                    Info
                </h2>

                <div class="info-stat__table">
                    <div class="info-stat__row">
                        <div class="info-stat__column info-stat__column_name">
                            country
                        </div>

                        <div class="info-stat__column">
                            <?= $brandModel->getCountryName() ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="car-info__common-info common-info">
            <div class="common-info__content">
                <h2 class="common-info__title stat-title">
                    Line Models
                </h2>

                <div class="common-info__line">
                </div>

                <ul class="common-info__list">
                    <?php if(empty($data->getModelList())): ?>
                        <li class='common-info__item'>
                            <div class='common-info__link'>
                                empty
                            </div>
                        </li>
                    <?php endif; ?>

                    <?php foreach ($data->getModelList() as $item): ?>
                        <li class='common-info__item'>
                            <a
                                href='/carModel?brand=<?= $brandModel->getId() ?>&line=<?= $data->getId() ?>&model=<?= $item->getId() ?>'
                                class='common-info__link'
                            >
                                <?= $item->getName() ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </section>
    </div>
</div>
