<?php
/**
 * @var App\Blocks\ModelBlock $this
 * @var App\Models\Model $data
 * @var App\Models\BrandModel $brandModel
 * @var App\Models\LineModel $lineModel
 */
?>

<?php $data = $this->getData() ?>
<?php $brandModel = $this->getChildModels()['BrandModel'] ?>
<?php $lineModel  = $this->getChildModels()['LineModel'] ?>

<div class="car-info block">
    <section class="car-info__img">
        <form
            class="form"
            method="post"
            action="/carModel"
        >
            <div class="form__row">
                <a>
                    ID:
                </a>
                <input
                    class="form__input"
                    type="number"
                    value="<?= $data->getId() ?>"
                    readonly
                    name="modelId"
                >
            </div>
            <div class="form__row">
                <a>
                    Name:
                </a>
                <input
                    class="form__input"
                    type="text"
                    value="<?= $data->getName() ?>"
                    name="modelName"
                >
            </div>
            <div class="form__row">
                <a>
                    Year:
                </a>
                <input
                    class="form__input"
                    type="number"
                    value="<?= $data->getYear() ?>"
                    name="modelYear"
                >
            </div>
            <div class="form__row">
                <a>
                    Previous ID:
                </a>
                <input
                    class="form__input"
                    type="number"
                    value="<?= $data->getPreviousId() ?>"
                    name="previousId"
                >
            </div>
            <input type="submit" value="SUBMIT">
        </form>
    </section>

    <h1 class="car-info__title">
        <?= $this->getHeader() ?>
    </h1>

    <div class="info">
        <section class="info__info-stat info-stat">
            <div class="info-stat__content">
                <h2 class="info-stat__title stat-title">
                    Info
                </h2>

                <div class="info-stat__table">
                    <div class="info-stat__row">
                        <div class="info-stat__column info-stat__column_name">
                            country
                        </div>

                        <div class="info-stat__column">
                            <?= $brandModel->getCountryName() ?>
                        </div>
                    </div>

                    <div class="info-stat__row">
                        <div class="info-stat__column info-stat__column_name">
                            year
                        </div>

                        <div class="info-stat__column">
                            <?= $data->getYear() ?>
                        </div>
                    </div>

                    <div class="info-stat__row">
                        <div class="info-stat__column info-stat__column_name">
                            previous
                        </div>

                        <a
                            href="/carModel?brand=<?= $brandModel->getId() ?>&line=<?= $lineModel->getId() ?>&model=<?= $data->getPreviousId() ?>"
                            class="info-stat__column"
                        >
                            <?= $data->getPreviousName() ?>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
