<?php
/**
 * @var App\Blocks\BrandBlock $this
 * @var App\Models\Brand $data
 * @var App\Models\Line $item
 */
?>

<?php $data = $this->getData() ?>

<div class="car-info block">
    <section class="car-info__img">
        <a class="delete" href="/carBrandDelete?id=<?= $data->getId() ?>">
            <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M15 0C6.72923 0 0 6.72923 0 15C0 23.2708 6.72923 30 15 30C23.2708 30 30 23.2708 30 15C30 6.72923 23.2708 0 15 0ZM15 2.30769C22.0235 2.30769 27.6923 7.97654 27.6923 15C27.6923 22.0235 22.0235 27.6923 15 27.6923C7.97654 27.6923 2.30769 22.0235 2.30769 15C2.30769 7.97654 7.97654 2.30769 15 2.30769ZM10.6385 8.97692L8.97692 10.6385L13.3431 15L8.97923 19.3615L10.6408 21.0231L15 16.6581L19.3615 21.0196L21.0231 19.3615L16.6581 15L21.0196 10.6385L19.3615 8.97692L15 13.3431L10.6385 8.97923V8.97692Z" fill="#D99BFF"/>
            </svg>
        </a>

        <form
            class="form"
            method="post"
            action="/carBrand"
        >
            <div class="form__row">
                <a>
                    ID:
                </a>
                <input
                    class="form__input"
                    type="number"
                    value="<?= $data->getId() ?>"
                    readonly
                    name="id"
                >
            </div>
            <div class="form__row">
                <a>
                    Name:
                </a>
                <input
                    class="form__input"
                    type="text"
                    value="<?= $this->normalizeData($data->getName()) ?>"
                    name="name"
                >
            </div>
            <div class="form__row">
                <a>
                    Country ID:
                </a>
                <input
                    class="form__input"
                    type="text"
                    value="<?= $data->getCountryId() ?>"
                    name="countryId"
                >
            </div>
            <?php $this->renderChildBlock('csrf-token-input'); ?>
            <input type="submit" value="SUBMIT">
        </form>
    </section>

    <h1 class="car-info__title">
        <?= $this->getHeader() ?>
    </h1>

    <div class="info">
        <section class="info-stat">
            <div class="info-stat__content">
                <h2 class="info-stat__title stat-title">
                    Info
                </h2>

                <div class="info-stat__table">
                    <div class="info-stat__row">
                        <div class="info-stat__column info-stat__column_name">
                            country
                        </div>

                        <div class="info-stat__column">
                            <?= $this->normalizeData($data->getCountryName()); ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="car-info__common-info common-info">
            <div class="common-info__content">
                <h2 class="common-info__title stat-title">
                    Car line
                </h2>

                <div class="common-info__line">
                </div>

                <ul class="common-info__list">
                    <?php if(empty($data->getLineList())): ?>
                        <li class='common-info__item'>
                            <a class="common-info__link">
                                empty
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php foreach ($data->getLineList() as $item): ?>
                        <li class='common-info__item'>
                            <a
                                href='/carLine?brand=<?= $data->getId() ?>&line=<?= $item->getId() ?>'
                                class='common-info__link'
                            >
                                <?= $this->normalizeData($item->getName()) ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </section>
    </div>

</div>
