<?php
/**
 * @var App\Blocks\BrandBlock $this
 * @var App\Models\Brand $data
 * @var App\Models\Line $item
 */
?>

<?php $data = $this->getData() ?>

<div class="car-info block">
    <section class="car-info__img">
        <form
            class="form"
            method="post"
            action="/carBrand"
        >
            <div class="form__row">
                <a>
                    ID:
                </a>
                <input
                    class="form__input"
                    type="number"
                    value="<?= $data->getId() ?>"
                    readonly
                    name="id"
                >
            </div>
            <div class="form__row">
                <a>
                    Name:
                </a>
                <input
                    class="form__input"
                    type="text"
                    value="<?= $data->getName() ?>"
                    name="name"
                >
            </div>
            <div class="form__row">
                <a>
                    Country ID:
                </a>
                <input
                    class="form__input"
                    type="text"
                    value="<?= $data->getCountryId() ?>"
                    name="countryId"
                >
            </div>
            <input type="submit" value="SUBMIT">
        </form>
    </section>

    <h1 class="car-info__title">
        <?= $this->getHeader() ?>
    </h1>

    <div class="info">
        <section class="info-stat">
            <div class="info-stat__content">
                <h2 class="info-stat__title stat-title">
                    Info
                </h2>

                <div class="info-stat__table">
                    <div class="info-stat__row">
                        <div class="info-stat__column info-stat__column_name">
                            country
                        </div>

                        <div class="info-stat__column">
                            <?= $data->getCountryName(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="car-info__common-info common-info">
            <div class="common-info__content">
                <h2 class="common-info__title stat-title">
                    Car line
                </h2>

                <div class="common-info__line">
                </div>

                <ul class="common-info__list">
                    <?php if(empty($data->getLineList())): ?>
                        <li class='common-info__item'>
                            <a class="common-info__link">
                                empty
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php foreach ($data->getLineList() as $item): ?>
                        <li class='common-info__item'>
                            <a
                                href='/carLine?brand=<?= $data->getId() ?>&line=<?= $item->getId() ?>'
                                class='common-info__link'
                            >
                                <?= $item->getName() ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </section>
    </div>

</div>
