<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main - AUTO</title>

    <?php
    require_once APP_ROOT . '/App/Templates/stylesheet.phtml';
    require_once APP_ROOT . '/App/Templates/header.phtml';
    ?>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,600;0,700;1,300&display=swap" rel="stylesheet">
</head>
<body>

<?= render_header(1) ?>

<div class="description block">
    <div class="description__content">
        <section class="description__img"></section>

        <section class="description__text">
            <div class="description__text-content">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
            </div>

            <a class="description__button button">
                main
            </a>

            <svg class="description__background" width="122" height="104" viewBox="0 0 122 104" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="10" cy="94" r="10" fill="#F8E6FF"/>
                <circle cx="44" cy="94" r="10" fill="#F8E6FF"/>
                <circle cx="78" cy="94" r="10" fill="#F8E6FF"/>
                <circle cx="112" cy="94" r="10" fill="#F8E6FF"/>
                <circle cx="10" cy="42" r="10" fill="#F8E6FF"/>
                <circle cx="44" cy="42" r="10" fill="#F8E6FF"/>
                <circle cx="78" cy="42" r="10" fill="#F8E6FF"/>
                <circle cx="112" cy="42" r="10" fill="#F8E6FF"/>
                <circle cx="10" cy="10" r="10" fill="#F8E6FF"/>
                <circle cx="44" cy="10" r="10" fill="#F8E6FF"/>
                <circle cx="78" cy="10" r="10" fill="#F8E6FF"/>
                <circle cx="112" cy="10" r="10" fill="#F8E6FF"/>
                <circle cx="10" cy="69" r="10" fill="#F8E6FF"/>
                <circle cx="44" cy="69" r="10" fill="#F8E6FF"/>
                <circle cx="78" cy="69" r="10" fill="#F8E6FF"/>
                <circle cx="112" cy="69" r="10" fill="#F8E6FF"/>
            </svg>
        </section>
    </div>
</div>

<div class="vehicle block">
    <section class="vehicle__text">
        <div class="vehicle__content-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
        </div>

        <a class="vehicle__button button">
            main
        </a>
    </section>

    <section class="vehicle__img">
    </section>
</div>

<div class="faq block">
    <div class="faq__content">
        <section class="faq__section">
            <div class="faq__text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </div>

            <a class="faq__button button">
                main
            </a>
        </section>

        <section class="faq__section">
            <div class="faq__text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </div>

            <a class="faq__button button">
                main
            </a>
        </section>

        <section class="faq__section">
            <div class="faq__text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </div>

            <a class="faq__button button">
                main
            </a>
        </section>
    </div>
</div>

<?php
require APP_ROOT . '/App/Templates/footer.phtml';
?>

</body>
</html>