<?php
/**
 * @var App\Blocks\RegistrationBlock $this
 */
$session = \App\Models\Session\Session::getInstance();
$errMsg = $session->getError()
?>
<div class="registration block">
    <section class="registration__content">
        <h1 class="registration__title">
            <?= $this->getHeader() ?>
        </h1>

        <form
            class="registration__form"
            action="/login"
            method="post"
        >
            <div class="registration__column registration__column_margined">
                <input
                    class="registration__input"
                    type="email"
                    name="email"
                    placeholder="Email"
                >
                <input
                    class="registration__input registration__button"
                    type="submit"
                    value="SUBMIT"
                >
            </div>

            <div class="registration__column">
                <input
                    class="registration__input"
                    type="password"
                    name="pass"
                    placeholder="Pass"
                >
            </div>
        </form>
    </section>

    <div class="registration__img">
        <?php if ($errMsg) : foreach ($errMsg as $error) : ?>
            <div class="error">
                <?= $error ?>
            </div>
        <?php endforeach; endif; ?>
    </div>
</div>
