<?php
/**
 * @var App\Blocks\RegistrationBlock $this
 */
?>

<div class="registration block">
    <section class="registration__content">
        <h1 class="registration__title">
            <?= $this->getHeader() ?>
        </h1>

        <form
            class="registration__form"
            action="/registration"
            method="post"
        >
            <div class="registration__column registration__column_margined">
                <input
                    class="registration__input"
                    type="email"
                    name="email"
                    placeholder="Email"
                >
                <input
                    class="registration__input registration__button"
                    type="submit"
                    value="SUBMIT"
                >
            </div>

            <div class="registration__column">
                <input
                    class="registration__input"
                    type="password"
                    name="pass"
                    placeholder="Pass"
                >
                <input
                    class="registration__input"
                    type="password"
                    name="repass"
                    placeholder="Re-pass"
                >
                <input
                    class="registration__input"
                    type="text"
                    name="csrfToken"
                    value="<?= $this->getCsrfToken() ?>"
                    hidden
                >
            </div>
        </form>
    </section>

    <div class="registration__img">

    </div>
</div>
