<?php
/**
 * @var App\Blocks\UserCarsBlock $this
 * @var App\Models\AbstractCarModel[] $data
 */
$data = $this->getChildCars();
?>
<div class="cars block">
    <section
        class="cars__content"
    >
        <h1 class="cars__title">
            <?= $this->getHeader() ?>
        </h1>

        <ul class="cars__list">
            <?php foreach ($data as $item): ?>
            <li class="cars__item">
                <h5 class="cars__car-title">
                    <?= $this->normalizeData($item->getName()) ?>
                </h5>

                <div class="cars__down-line">

                </div>

                <div class="cars__car-info">
                    <div class="cars__row">
                        <a class="cars__info-title">
                            num
                        </a>

                        <a class="cars__info-value">
                            <?= $item->getNum() ?>
                        </a>
                    </div>

                    <div class="cars__row">
                        <a class="cars__info-title">
                            vrc
                        </a>

                        <a class="cars__info-value">
                            <?= $item->getVrc() ?>
                        </a>
                    </div>
                </div>

                <a class="cars__button" href="/specificCar?car=<?= $item->getId() ?>">
                    go to >
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </section>

    <div class="cars__img">
        <nav
            class="profile-nav profile-nav_margined"
        >
            <div class="profile-nav__item">
                <div class="profile-nav__link-line">

                </div>

                <a
                    class="profile-nav__link"
                    href="/profileInfo"
                >
                    my info
                </a>
            </div>

            <div class="profile-nav__item">
                <div class="profile-nav__link-line profile-nav__link-line_active">

                </div>

                <a
                    class="profile-nav__link profile-nav__link_active"
                    href="/userCars"
                >
                    my cars
                </a>
            </div>
        </nav>
    </div>
</div>