<footer class="header-footer block">
    <div class="footer">
        <section class="footer__text">
            <div class="footer__content-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </div>

            <span class="footer__copyright">
        © 2022 Taganrog. All rights reserved
      </span>
        </section>

        <nav class="footer__nav">
            <h6 class="footer__nav-header">
                Links
            </h6>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>
        </nav>

        <nav class="footer__nav">
            <h6 class="footer__nav-header">
                Links
            </h6>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>

            <a
                href=""
                class="footer__link"
            >
                main
            </a>
        </nav>

        <div class="footer__logo logo">
            <div class="footer__logo_padding">
                <a class="logo__word">
                    auto
                </a>

                <a class="logo__word logo__word_light">
                    auto
                </a>

                <a class="logo__word">
                    auto
                </a>

                <a class="logo__word logo__word_light">
                    auto
                </a>

                <a class="logo__word">
                    auto
                </a>
            </div>
        </div>
    </div>
</footer>